services:
  teensy-uxrce-agent:
    image: antbre/uxrce_agent
    privileged: true
    network_mode: 'host'
    command: serial --dev /dev/ttyACM0

  px4-uxrce-agent:
    image: antbre/uxrce_agent
    privileged: true
    network_mode: 'host'
    command: serial --dev /dev/ttyAMA0 -b 921600

  #tactile-sensor-driver:
  #  image: antbre/tactile_sensor_driver
  #  privileged: true 
  #  network_mode: 'host'

  # Start state machine